name: build_Release
on:
  push:
    branches:
      - master
    paths-ignore:
      - ".gitignore"
  workflow_dispatch:
 
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Procursus
        uses: wwg135/procursus-action@main
        with:
          packages: ldid findutils sed coreutils trustcache make

      - name: Install THEOS
        run: |
          set -x
          export BASEDIR="$(pwd)"
          export THEOS="${BASEDIR}/theos"
          mkdir -p $THEOS
          curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos >> install-theos.sh
          gsed -E "/^\s*get_theos\s*$/,+1 s/^(\s*)(get_sdks)\s*$/\1mkdir -p \${THEOS}\/sdks\n\1touch \${THEOS}\/sdks\/sdk\n\1\2/g" -i install-theos.sh
          bash install-theos.sh
          cd $BASEDIR

      - name: Set Env
        run: |
          set -x
          SHASH=$(git rev-parse --short HEAD)
          echo "shT=$(TZ=UTC-8 date +'%Y-%m-%d'' ''%H:%M:%S')" >> $GITHUB_ENV
          echo "shorthash=${SHASH}" >> $GITHUB_ENV

      - name: Print Env
        run: |
          set -x
          echo ${{ env.shT }}

      - name: Build ipa
        run: |
          set -x
          sudo security import Exploits/fastPath/arm.pfx -k /Library/Keychains/System.keychain -P password -A
          sed -i '' "s/AAA/更新时间/g" ./Dopamine/Dopamine/UI/Views/JailbreakView.swift
          sed -i '' "s/AAB/${{ env.shT }}/g" ./Dopamine/Dopamine/UI/Views/JailbreakView.swift
          export BASEDIR="$(pwd)"
          export THEOS="${BASEDIR}/theos"
          gmake -j$(sysctl -n hw.physicalcpu)
          cp -a Dopamine/Dopamine.tipa Dopamine/Dopamine.ipa

      - name: Upload Artifact
        id: dopamine-upload
        uses: actions/upload-artifact@v3
        with:
          name: Dopamine
          path: |
            ${{ github.workspace }}/Dopamine/Dopamine.ipa
